### ISSUE TITLE
Etherpad crashes on input errors in ep_frontend_community

### ISSUE THREAD

**Issue by tbe** [reality/ep_frontend_community#10]
If we try to add a non-existant user to a group, etherpad crashes

```
[2015-04-16 12:22:26.234] [ERROR] console - ep_frontend_community: One or more users are not yet registered
[2015-04-16 12:22:26.240] [ERROR] console - Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
    at ServerResponse.res.setHeader (/home/etherpad/etherpad-lite/node_modules/ep_frontend_community/node_modules/express/node_modules/connect/lib/patch.js:59:22)
    at ServerResponse.header (/home/etherpad/etherpad-lite/src/node_modules/express/lib/response.js:700:10)
    at ServerResponse.send (/home/etherpad/etherpad-lite/src/node_modules/express/lib/response.js:154:12)
    at ServerResponse.res.send (/home/etherpad/etherpad-lite/src/node/hooks/express/webaccess.js:101:14)
    at ServerResponse.json (/home/etherpad/etherpad-lite/src/node_modules/express/lib/response.js:240:15)
    at ServerResponse.send (/home/etherpad/etherpad-lite/src/node_modules/express/lib/response.js:142:21)
    at ServerResponse.res.send (/home/etherpad/etherpad-lite/src/node/hooks/express/webaccess.js:101:14)
    at /home/etherpad/etherpad-lite/node_modules/ep_frontend_community/hooks.js:1310:37
    at Query._callback (/home/etherpad/etherpad-lite/node_modules/ep_frontend_community/hooks.js:217:13)
```

**Comment by colttt** [comment]
i can confirm that, the same if you will create an already existing pad:
```
[2015-08-20 15:51:07.570] [ERROR] console - ep_frontend_community: MySQLError: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
[2015-08-20 15:51:07.575] [ERROR] console - Async Stacktrace:
    at /opt/etherpad/etherpad-lite/src/node/db/GroupManager.js:308:8

apierror: padName does already exist
    at /opt/etherpad/etherpad-lite/src/node/db/GroupManager.js:282:20
    at Object.callback (/opt/etherpad/etherpad-lite/src/node/db/PadManager.js:193:7)
    at /opt/etherpad/etherpad-lite/src/node_modules/ueberDB/CloneAndAtomicLayer.js:100:17
    at /opt/etherpad/etherpad-lite/src/node_modules/ueberDB/CacheAndBufferLayer.js:185:7
    at Query._callback (/opt/etherpad/etherpad-lite/src/node_modules/ueberDB/mysql_db.js:115:5)
    at Query.Sequence.end (/opt/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Query._handleFinalResultPacket (/opt/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
    at Query.EofPacket (/opt/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
    at Protocol._parsePacket (/opt/etherpad/etherpad-lite/src/node_modules/ueberDB/node_modules/mysql/lib/protocol/Protocol.js:271:23)
[2015-08-20 15:51:07.576] [INFO] console - graceful shutdown...
[2015-08-20 15:51:07.645] [INFO] console - db sucessfully closed.
```

**Comment by pabelenda** [comment]
Hi,

it is failing to me while trying to add a user into a group.

`[2016-04-26 17:43:33.402] [ERROR] console - Error: write EPIPE
    at errnoException (net.js:901:11)
    at Object.afterWrite (net.js:718:19)
[2016-04-26 17:43:33.402] [INFO] console - graceful shutdown...
[2016-04-26 17:43:33.404] [ERROR] console - Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
[2016-04-26 17:43:33.500] [INFO] console - db sucessfully closed.
`
