### ISSUE TITLE
Mysql error | ep_frontend_community | etherpad 

### ISSUE THREAD

**Issue by pajaro23** [reality/ep_frontend_community#17]
Hello, I'm setting up a plugin for etherpad but I get the following error, but I have not had success to solve it.

 console - TypeError: Cannot read property '0' of null
    at /var/www/site/softw/etherpad-lite-1.6.1/node_modules/ep_frontend_community/hooks.js:1819:58
    at Query._callback (/var/www/site/softw/etherpad-lite-1.6.1/node_modules/ep_frontend_community/hooks.js:203:13)
    at Query.Sequence.end (/var/www/site/softw/etherpad-lite-1.6.1/node_modules/mysql/lib/protocol/sequences/Sequence.js:75:24)
    at Query._handleFinalResultPacket (/var/www/site/softw/etherpad-lite-1.6.1/node_modules/mysql/lib/protocol/sequences/Query.js:143:8)
    at Query.EofPacket (/var/www/site/softw/etherpad-lite-1.6.1/node_modules/mysql/lib/protocol/sequences/Query.js:127:8)
    at Protocol._parsePacket (/var/www/site/softw/etherpad-lite-1.6.1/node_modules/mysql/lib/protocol/Protocol.js:172:24)
    at Parser.write (/var/www/site/softw/etherpad-lite-1.6.1/node_modules/mysql/lib/protocol/Parser.js:62:12)
    at Protocol.write (/var/www/site/softw/etherpad-lite-1.6.1/node_modules/mysql/lib/protocol/Protocol.js:37:16)
    at Socket.ondata (_stream_readable.js:542:20)

**Comment by lpagliari** [comment]
Looking around [line 1819 on hooks.js](https://github.com/reality/ep_frontend_community/blob/master/hooks.js#L1819), you can see some access to `property '0'` of some objects: `currUser[0]` and `currGroup[0]`. Not sure why they are not set, but maybe other issues here might give you a hint.
